version: '3.8'

services:
  shop_framework:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: shop_framework
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx_log:/var/log/nginx
      - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
    links:
      - mysql

  mysql:
    image: mysql:5.6
    container_name: shop_mysql
    ports:
      - "3308:3306"
    volumes:
      - ./docker/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0huuthinh0
